import { getStore } from '@netlify/blobs';

export default async function handler(req) {
  const store = getStore('oltc-state');
  const action = new URL(req.url).searchParams.get('action');

  if (action === 'get') {
    const [codesRaw, countRaw] = await Promise.all([
      store.get('last-codes-v2', { type: 'json' }),
      store.get('participant-count', { type: 'text' })
    ]);
    return Response.json({
      codes: codesRaw ?? [32, 14, 78],
      participantCount: countRaw ? parseInt(countRaw) : 0
    });
  }

  // validate-token: trust the token (generated by the server, delivered via QR) — just increment count
  if (action === 'validate-token' && req.method === 'POST') {
    let body;
    try { body = await req.json(); } catch {
      return Response.json({ valid: false, error: 'Ongeldig verzoek.' }, { status: 400 });
    }
    const { token } = body;
    if (!token) return Response.json({ valid: false, error: 'Geen token.' }, { status: 400 });
    try {
      const decoded = Buffer.from(token.replace(/-/g, '+').replace(/_/g, '/'), 'base64').toString('utf8');
      const codes = decoded.split(',').map(Number);
      if (codes.length !== 3 || codes.some(isNaN)) throw new Error();
    } catch {
      return Response.json({ valid: false, error: 'Ongeldig token.' }, { status: 400 });
    }
    const countRaw = await store.get('participant-count', { type: 'text' });
    const newCount = (countRaw ? parseInt(countRaw) : 0) + 1;
    await store.set('participant-count', String(newCount));
    return Response.json({ valid: true, participantNumber: newCount });
  }

  if (action === 'validate' && req.method === 'POST') {
    let body;
    try {
      body = await req.json();
    } catch {
      return Response.json({ valid: false, error: 'Ongeldig verzoek.' }, { status: 400 });
    }

    const { codes } = body;
    if (!Array.isArray(codes) || codes.length !== 3 || codes.some(c => typeof c !== 'number' || isNaN(c))) {
      return Response.json({ valid: false, error: 'Drie geldige nummers vereist.' }, { status: 400 });
    }

    const [lastCodesRaw, countRaw] = await Promise.all([
      store.get('last-codes-v2', { type: 'json' }),
      store.get('participant-count', { type: 'text' })
    ]);

    const lastCodes = lastCodesRaw ?? [32, 14, 78];
    const currentCount = countRaw ? parseInt(countRaw) : 0;

    const failedSlots = codes.map((n, i) =>
      (n <= lastCodes[i] || n > lastCodes[i] + 4) ? i : null
    ).filter(i => i !== null);

    if (failedSlots.length > 0) {
      return Response.json({
        valid: false,
        error: 'Een of meer codes zijn al eerder gebruikt of verlopen.',
        slots: failedSlots
      });
    }

    const newCount = currentCount + 1;
    await Promise.all([
      store.set('last-codes-v2', JSON.stringify(codes)),
      store.set('participant-count', String(newCount))
    ]);

    return Response.json({ valid: true, participantNumber: newCount });
  }

  return Response.json({ error: 'Onbekende actie.' }, { status: 400 });
}

