import { getStore } from '@netlify/blobs';

const CORS = {
  'Access-Control-Allow-Origin':  '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

function json(body, init = {}) {
  return new Response(JSON.stringify(body), {
    ...init,
    headers: { 'Content-Type': 'application/json', ...CORS, ...(init.headers ?? {}) },
  });
}

export default async function handler(req) {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });

  const store = getStore('oltc-state');
  const action = new URL(req.url).searchParams.get('action');

  if (action === 'get') {
    const [codesRaw, countRaw] = await Promise.all([
      store.get('last-codes-v2', { type: 'json' }),
      store.get('participant-count', { type: 'text' })
    ]);
    return json({
      codes: codesRaw ?? [32, 14, 78],
      participantCount: countRaw ? parseInt(countRaw) : 0
    });
  }

  // validate-token: trust the token (generated by the server, delivered via QR) — just increment count
  if (action === 'validate-token' && req.method === 'POST') {
    let body;
    try { body = await req.json(); } catch {
      return json({ valid: false, error: 'Ongeldig verzoek.' }, { status: 400 });
    }
    const { token } = body;
    if (!token) return json({ valid: false, error: 'Geen token.' }, { status: 400 });
    try {
      const decoded = Buffer.from(token.replace(/-/g, '+').replace(/_/g, '/'), 'base64').toString('utf8');
      const codes = decoded.split(',').map(Number);
      if (codes.length !== 3 || codes.some(isNaN)) throw new Error();
    } catch {
      return json({ valid: false, error: 'Ongeldig token.' }, { status: 400 });
    }
    const countRaw = await store.get('participant-count', { type: 'text' });
    const newCount = (countRaw ? parseInt(countRaw) : 0) + 1;
    await store.set('participant-count', String(newCount));
    return json({ valid: true, participantNumber: newCount });
  }

  if (action === 'validate' && req.method === 'POST') {
    let body;
    try {
      body = await req.json();
    } catch {
      return json({ valid: false, error: 'Ongeldig verzoek.' }, { status: 400 });
    }

    const { codes } = body;
    if (!Array.isArray(codes) || codes.length !== 3 || codes.some(c => typeof c !== 'number' || isNaN(c))) {
      return json({ valid: false, error: 'Drie geldige nummers vereist.' }, { status: 400 });
    }

    const [lastCodesRaw, countRaw] = await Promise.all([
      store.get('last-codes-v2', { type: 'json' }),
      store.get('participant-count', { type: 'text' })
    ]);

    const lastCodes = lastCodesRaw ?? [32, 14, 78];
    const currentCount = countRaw ? parseInt(countRaw) : 0;

    const failedSlots = codes.map((n, i) =>
      (n <= lastCodes[i] || n > lastCodes[i] + 4) ? i : null
    ).filter(i => i !== null);

    if (failedSlots.length > 0) {
      return json({
        valid: false,
        error: 'Een of meer codes zijn al eerder gebruikt of verlopen.',
        slots: failedSlots
      });
    }

    const newCount = currentCount + 1;
    await Promise.all([
      store.set('last-codes-v2', JSON.stringify(codes)),
      store.set('participant-count', String(newCount))
    ]);

    return json({ valid: true, participantNumber: newCount });
  }

  // set-name: webapp signals that a participant entered their name
  if (action === 'set-name' && req.method === 'POST') {
    let body;
    try { body = await req.json(); } catch {
      return json({ error: 'Invalid body' }, { status: 400 });
    }
    const { token, name } = body;
    if (!token || !name) return json({ error: 'Missing token or name' }, { status: 400 });
    await store.set(`start-${token}`, JSON.stringify({ name, startedAt: Date.now() }));
    return json({ ok: true });
  }

  // poll-start: installation polls to know when participant is ready
  if (action === 'poll-start') {
    const token = new URL(req.url).searchParams.get('token');
    if (!token) return json({ started: false });
    const raw = await store.get(`start-${token}`, { type: 'json' });
    if (!raw) return json({ started: false });
    return json({ started: true, name: raw.name });
  }

  return json({ error: 'Onbekende actie.' }, { status: 400 });
}

